### ISSUE TITLE
Alex mobs error

### ISSUE THREAD

**Issue by MrMik3yyy** [MarkusBordihn/BOs-Adaptive-Performance-Tweaks#10]
**Describe the bug**
I am noticing that a tammed racoon from Alex's mobs that is leashed up is causing an "Unknown entity name for entity LeashFenceKnotEntity" error in console

**To Reproduce**
1. tame a racoon
2. tie it up to a fence with a lead
3. look at console and see the error mentioning its location with XYZ cords

**Expected behavior**
i thought it would remove the recoon but thankfully it hasnt, but still worried since it notices that mob. i just dont want it to be removed cause it was tammed and is fine

**Screenshots**
![Screenshot 2022-05-20 193354](https://user-images.githubusercontent.com/105953167/169624875-b3c92a91-66b0-4118-82a6-3df54fad9a5a.jpg)
![Base Profile Screenshot 2022 05 20 - 19 34 21 60](https://user-images.githubusercontent.com/105953167/169624893-440d7475-721c-409b-878c-070d2e7d5ccd.png)

**Debugging**
cant find the log file anywhere 

**Is the issue happening in combination with other mods? (If yes, please provide a full list)**
Alex's mobs https://www.curseforge.com/minecraft/mc-mods/alexs-mobs

**Additional context**
i dont see any other issue with the other mods i have within the server, the only one im noticing it mentioning errors or issues to is Alex's mobs mod

**Comment by MarkusBordihn** [comment]
Thanks a lot for the report I will add the item to the ignore list so that the warning message will be removed with the next update.
In general it should not cause any issue, but it shows me that I need to exclude specific entities from further checks to avoid possible side effects or issues. ;)

**Comment by MarkusBordihn** [comment]
Should be fixed with https://www.curseforge.com/minecraft/mc-mods/adaptive-performance-tweaks-core/files/3800710
Thanks again for the report. ;)
