### ISSUE TITLE
The Mod Optimizer seems to disable CraftingTweaks even if its required by the server

### ISSUE THREAD

**Issue by Polarolouis** [MarkusBordihn/BOs-Adaptive-Performance-Tweaks#11]
**Describe the bug**
Using `adaptive_performance_tweaks_1.18.2-3.4.0`
Mod Optimizer disables CraftingTweaks even if in craftingtweaks-common.toml there is a [common] field and thus causes impossibility to connect to the server using APTweaks.

**To Reproduce**
1. Have APTweaks installed on the server with CraftingTweaks (craftingtweaks-forge-1.18.1-14.0.2)
2. Use the following craftingtweaks-common.toml : 
```
[client]
	#This option is toggled by the 'Toggle Buttons' key that can be defined in the Controls settings.
	hideButtons = false
	#If set to true, right-clicking the result slot in a crafting table will craft a full stack.
	rightClickCraftsStack = true
	#Set this to true if you don't want the tweak buttons' tooltips to show.
	hideButtonTooltips = false
	#We both know JEI is much better. This option hides Vanilla's crafting book button instead of moving it.
	hideVanillaCraftingGuide = false
	#Set to 'DEFAULT' to enable both buttons and hotkeys. Set to 'BUTTONS' to enable buttons only. Set to 'HOTKEYS' to enable hotkeys only.
	#Allowed Values: DEFAULT, BUTTONS, HOTKEYS, DISABLED
	craftingTweaksMode = "DEFAULT"
	#Add mod ids here of mods that you wish to disable Crafting Tweaks support for.
	disabledAddons = []

[common]
	#Set this to true if you want the (de)compress feature to work outside of crafting GUIs (only works if installed on server)
	compressAnywhere = false
	#A list of modid:name entries that will not be crafted by the compress key.
	compressBlacklist = ["minecraft:sandstone", "minecraft:iron_trapdoor"]
```

**Client logs**
```
21:01:43.448
net.minecraftforge.network.NetworkRegistry
Netty Client IO #2
Channels [craftingtweaks:network] rejected their server side version number
21:01:43.448
net.minecraftforge.network.HandshakeHandler
Netty Client IO #2
Terminating connection with server, mismatched mod list
```

**Comment by MarkusBordihn** [comment]
Thanks for the report, but this means that the "Crafting Tweaks" description is wrong, see:
`Bi-optional. Only those who want to use it need to install it, and if the server doesn't have it installed, it will still work for people who do have it installed.`

Source: https://www.curseforge.com/minecraft/mc-mods/crafting-tweaks

I will remove it from the mods database to solve the issue.

**Comment by MarkusBordihn** [comment]
Should be fixed with https://www.curseforge.com/minecraft/mc-mods/adaptive-performance-tweaks-mods/files/3800554

**Comment by Polarolouis** [comment]
It fixed it thank you 😄 !
