### ISSUE TITLE
1.19 Latest Forge Crash

### ISSUE THREAD

**Issue by LoxiGoose** [MarkusBordihn/BOs-Adaptive-Performance-Tweaks#17]
**Describe the bug**
The mod crashes upon starting up Minecraft

**To Reproduce**
1. Start up Minecraft on latest version of Forge
2. Crashed

**Expected behavior**
For the game to start up correctly

Minecraft Version: 1.19
Forge Version: 41.0.94
Mod Version: 4.1.1

Crash Log: https://mclo.gs/qVNdTUk

**Comment by MarkusBordihn** [comment]
Thanks for the report, should be fixed with f046e188c5bc1624e38d52f2e3e5987b65c9c9bf.
