### ISSUE TITLE
Player protection no information ?

### ISSUE THREAD

**Issue by Avadonia** [MarkusBordihn/BOs-Adaptive-Performance-Tweaks#18]
Hello, i didn't much information on the player protection (child difficulty mode) what does it change exactly ? how 'child' is it, i have a new player on a modded server and it might help.

**Comment by MarkusBordihn** [comment]
Basically it makes the child player invisible (for mobs) and invulnerable (not immortal), so that other player could still fight bigger bosses but the child player is not attacked or dying every 5-10 mins.

But let me know if you have something else in mind and I could check if this is something which could be implemented to this mod.

**Comment by Avadonia** [comment]
One of my player might use it, would have prefered a damage reduction/damage increase % :p

**Comment by MarkusBordihn** [comment]
That's something which should be easy to add.  Let give me some days for testing. ;)

**Comment by Avadonia** [comment]
Thanks that's very nice of you :D

**Comment by MarkusBordihn** [comment]
Ok, was easier then I tough and was able to test it with 10 players online.

Should be online in the next hours over:

- https://www.curseforge.com/minecraft/mc-mods/adaptive-performance-tweaks-player/files/3879462
- https://www.curseforge.com/minecraft/mc-mods/adaptive-performance-tweaks-player/files/3879446

I added some additional configuration options so you are able to adjust the hurt damage decreasement (down to 0%) and the attack damage increasement (up to 1000%), additional you can enable/disable the invisible (for mobs) and invulnerable (not immortal).

Let me know if you run into any issues, but should work fine. ;)
