### ISSUE TITLE
Auto Deleting Backups

### ISSUE THREAD

**Issue by TheWookofWallST** [MarkusBordihn/BOs-Adaptive-Performance-Tweaks#20]
So I just installed your adaptive performance mods. Love them so far, but I did notice that it auto deletes the backups my FTB Backups mod creates and I can't seem to figure out if I can make it avoid that 1 folder or something. If that isn't already a thing I think that would be great

**Comment by MarkusBordihn** [comment]
Thanks for the report. But the mod is not *deleting* anything from FTB Backups, there is also no reference to ftbbackups2 in the code at all, see: https://github.com/MarkusBordihn/BOs-Adaptive-Performance-Tweaks/search?q=ftbbackups

I'm using FTB Backups myself and they have a "auto-delete" feature with a default of 6, so I assume that your older backups were auto-deleted by FTB Backups itself. You can change this limit in their config file `ftbbackups2.json` under *max_backups*.
