### ISSUE TITLE
1.19.2 Question - Does this mod respect tagged mobs?

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [MarkusBordihn/BOs-Adaptive-Performance-Tweaks#26]
I noticed my villages are golem less etc but I was wondering if the mod will respect using nametags (Which sole purpose is to make it so a mob does not despawn unless slain.) I figured I would ask in advance.

**Comment by MarkusBordihn** [comment]
All mobs which has a custom name or owned by a player are automatically excluded from any optimization.
Minecraft itself will still de-spawn them in certain instances regardless if they have a name tag or not.
