### ISSUE TITLE
Add COFH core Compat for 1.16.5 please and also Pixelmon if Possible please

### ISSUE THREAD

**Issue by Foxydapirate12** [MarkusBordihn/BOs-Adaptive-Performance-Tweaks#33]
**Is your feature request related to a problem? Please describe.**
I get this error in the console: _[13Jan2023 13:56:04.262] [Server thread/WARN] [APTweaks:EntityManager/]: Unknown entity name for entity ElectricArcEntity['entity.cofh_core.electric_arc'/26391, l='ServerLevel[PixelSluts]', x=3212.28, y=68.19, z=2916.63] (entity.cofh_core.electric_arc) in minecraft:overworld. Please report this issue under https://github.com/MarkusBordihn/BOs-Adaptive-Performance-Tweaks/issues/!_

**Describe the solution you'd like**
I suppose a compat update to fix it

**Describe alternatives you've considered**
Turning off the entitymanager

**Additional context**
![SharedScreenshot](https://user-images.githubusercontent.com/101042481/212465195-07e1f198-7088-4c6d-a14b-a082ed8da953.jpg)
Also sorry if this is an awful feature request, i just woke up and had one of my server admins complaining about it so i thought i'd make a feature request to atleast help bring attention to it.

**Comment by MarkusBordihn** [comment]
Thanks a lot for the report. I just released an update which should improve the compatibility for a lot of mods including Pixelmon.
See: https://www.curseforge.com/minecraft/mc-mods/adaptive-performance-tweaks/files/4332244

Unfortunately I'm not longer using 1.16.5 myself and have no running server with 1.16.5. 
It worked fine in the developer environment, but let me know if you see any specific issue on your server with this new version.

**Comment by Foxydapirate12** [comment]
Cheers Mate!!
