### ISSUE TITLE
1.18.X - 1.19.X Forge Client Side Mods Helper Wildcard Support

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [MarkusBordihn/BOs-Adaptive-Performance-Tweaks#34]
**Is your feature request related to a problem? Please describe.**

I would like wildcard support for mods blacklist; example ``TextruesRubidiumOptions-1.0.4-mc1.19.3 to TextruesRubidiumOptions*.jar``

**Describe the solution you'd like**

I would like wildcard support for mods blacklist; example ``TextruesRubidiumOptions-1.0.4-mc1.19.3 to TextruesRubidiumOptions*.jar``

**Describe alternatives you've considered**

There isn't any

**Additional context**

I would like wildcard support for mods blacklist; example ``TextruesRubidiumOptions-1.0.4-mc1.19.3 to TextruesRubidiumOptions*.jar``

**Comment by MarkusBordihn** [comment]
Thanks a lot for the feedback. Currently the mod already include a kind of wildcard support by automatically stripping out the versions numbers from the given file names.

The file name `TextruesRubidiumOptions-1.0.4-mc1.19.3` will basically match with anything like `TextruesRubidiumOptions-*-mc1.19.3`.
If this is not working for a specific use-case it would be great if you could provide an example to improve the version stripping.
