### ISSUE TITLE
1.19.3 and 1.18.2 Needs some more entries by default (Updated again)

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [MarkusBordihn/BOs-Adaptive-Performance-Tweaks#35]
I deleted the template because this was not that advanced.

Add the following entries.

rubidium-extra-0.4.16+mc1.19.3-build.56 (Sodium Clientside Based)
TextruesRubidiumOptions-1.0.4-mc1.19.3.jar (Sodium Clientside Based)

I have of course manually added both entries I just noticed they were missing.

**Comment by MarkusBordihn** [comment]
Thanks for the report. I will add them with the next update.

**Comment by P3rf3ctXZer0** [comment]
Torohealth 1.18.2

**Comment by P3rf3ctXZer0** [comment]
More Mods clearwater-1.18.2-1.8
