### ISSUE TITLE
[QUESTION] Does your mod work with ISNT

### ISSUE THREAD

**Issue by Camawama** [MarkusBordihn/BOs-Adaptive-Performance-Tweaks#37]
It Shall Not Tick is a mod that stops entities from ticking under certain conditions. I am wondering if your mod conflicts as they do similar things?

**Comment by Camawama** [comment]
https://github.com/nanite/ItShallNotTick/issues/26

**Comment by MarkusBordihn** [comment]
Adaptive Performance Tweaks is not really modify any ticking or so, it's only preventing the spawn of a specific amount of entities on a higher server load. Furthermore it's dynamically adjusting game rules and clustering items to avoid higher loads.

So from the technical side I see no "conflict", but *ItShallNotTick* using Mixin's / Core Modding, which could cause issues in general with other mods which modding the same functionality.
