### ISSUE TITLE
[1.16.5] Incompatibility with "Does Potato Tick?" mod, no mobs in the world

### ISSUE THREAD

**Issue by okzerus** [MarkusBordihn/BOs-Adaptive-Performance-Tweaks#39]
**Describe the bug**
after walking around in the world with DPT and APT installed (both latest versions), after a while mobs will entirely stop spawning.
only mobs that are generated with the world will appear (such as villagers or bees)
I have only enabled modules for items and experience orbs, but the issue still persists. deleting the APT fixes the issue, so I assume that modules are not being disabled entirely.

**To Reproduce**
1. Install Does Potato Tick 3.2 https://modrinth.com/mod/does-potato-tick/version/1.16.5-3.2
2. Install Adaptive Performance Tweaks 2.5.0 https://www.curseforge.com/minecraft/mc-mods/adaptive-performance-tweaks/files/4332244
3. Join the world
4. Load new chunks for 10-20 minutes, teleporting also works. simply /tp ~1000 ~ ~ and load the area, then repeat.
5. No mobs will appear at all.

**Expected behavior**
many mobs go brrrrrr player's ass

**Debugging**
will do later, because currently I'm not at PC. I hope that this is known bug or dev has any ideas how to fix it straight away without logs, but will provide later anyway

**Comment by MarkusBordihn** [comment]
Thanks for the report but unfortunately this is expected.
As soon you disable the ticking of an entity, this entity will no longer able to de-spawn and so still count to any mob limit.
In this case you could try to disable the "spawn" module or stop using such mods.

In general completely disabling the ticking of entity could lead to issues, so normally the ticking should be only throtteld, but not completely disabled.

**Comment by okzerus** [comment]
> Thanks for the report but unfortunately this is expected. As soon you disable the ticking of an entity, this entity will no longer able to de-spawn and so still count to any mob limit. In this case you could try to disable the "spawn" module or stop using such mods.
> 
> In general completely disabling the ticking of entity could lead to issues, so normally the ticking should be only throtteld, but not completely disabled.

I'm sorry for the late response! just as I said, I've already disabled all the modules possible, only the item module is active. but, the mobs are still not appearing at all. any workarounds for this?

also, no way for DPT to be deleted. it optimizes my modpack more than many other mods put together :(
any chances for the Adaptive Performance Tweaks: Items to be backported to the 1.16 version? :(

**Comment by huihiuhuai** [comment]
any chances for the Adaptive Performance Tweaks: Items to be backported to the 1.16 version? :(
