### ISSUE TITLE
Problem with the Raid

### ISSUE THREAD

**Issue by Willem07** [MarkusBordihn/BOs-Adaptive-Performance-Tweaks#40]
**The raid does not end**
![2023-03-06_15 19 37](https://user-images.githubusercontent.com/51959206/223109152-cf9d2a60-074c-4a81-8e60-a336ce889a8d.png)

mods:
> adaptive_performance_tweaks_spawn_1.18.2-3.18.0
> adaptive_performance_tweaks_core_1.18.2-3.18.0

**Comment by MarkusBordihn** [comment]
Thanks for the report. The issue should be fixed with the lastest update.
