### ISSUE TITLE
1.18.2/1.19.2 - When traveling away from spawns nothing spawns for players even when next to a spawner

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [MarkusBordihn/BOs-Adaptive-Performance-Tweaks#42]
**Describe the bug**
What using ``Adaptive Spawn`` and having at least 4 players there is no checks to make sure mobs still spawn.

**To Reproduce**
1. Add the spawn module
2. Get at least 4 players on a dedicated server
3. have the four of them walk in 4 different direction
4. eventually spawns just stop.

**Expected behavior**
Each player should have a spawn allowance or spawns should despawn when player is not nearby (Exception of Minecolonist.)

**Information**
Its been a bug for a while and obviously not one you can test solo I should have reported it back in 2020 sorry for that.

**Idea for Fix**
(Limit spawns based on open tps? This like your other mods would in theory allow more spawns when less players are on and less when lots of players are on. Also a radius around player is a great idea as well.)

**Comment by MarkusBordihn** [comment]
Thanks for the report could you please enable the debug mod when this is happening and sharing the log with the debug entries.

In general the spawn cap is already per player and per world, 
Furthermore the spawn cap is only activated when the server load is high.

There are basically the following possibilities for this:
- Your server is overloaded (server-load: very-high)
- The mobs reach the world cap (should be visible in the debug log)
- The mobs reach the player cap (should be visible in the debug log)
- Minecraft own cap happens (if you see no entries in the debug log, it means that the entities are capped by Minecraft or another mod)
- Something else

Let me know if you need more details on how to use the "debug" mode.

**Comment by P3rf3ctXZer0** [comment]
Happy to help - yes I will enable the debug and put it on my server just give me a couple hours playing Deadcells.

**Comment by P3rf3ctXZer0** [comment]
@MarkusBordihn - how do I enable debugging?

**Comment by MarkusBordihn** [comment]
You need to be in creative, op or on the server console so that this is working.

Enabled the debug with: `/aptweaks debug spawn true`
Disabled the debug with: `/aptweaks debug spawn false`

You should see a message like:
![image](https://user-images.githubusercontent.com/12183293/230215094-fb4310a1-08d1-4c10-b387-126c13a158dc.png)

The debug will be saved in the debug.log or last.log

You could also use `/aptweaks playerPositions` to see if all players are detected on the correct position.

**Comment by P3rf3ctXZer0** [comment]
I will be testing but right now I need sleep I will close this when I have 4 people to help me test and it is not an issue. (Solo testing is next to impossible.) If you ever wanted to test things directly on my server I will op you.

**Comment by P3rf3ctXZer0** [comment]
After adding ``Aggressive spawn`` controller I cannot make it happen. For now I will close this. Thanks for your patience with me I promise I only want stuff to work :D

**Comment by P3rf3ctXZer0** [comment]
After defeating end dragon only overworld spawns were working. We have a problem as my debug in 2 days was 192MB so I cannot upload via anything other than dropbox. Let me know if that is acceptable.

**Comment by MarkusBordihn** [comment]
Thanks for the feedback. First of all you should try to delete anything which is not relevant like "chats" or anything else which should not be available to the public.

In general I only need the debug from some time (1 hour) before and after (15 min) when spawning is no longer working.
I don't need a full 2 days log if the issue only happen on the last hour of day 2.

You could use something like [Pastebin.com](https://pastebin.com/) or [GitHub Gist](https://gist.github.com/).
I have no drop box account, but if the link is shared to the public I should be able to access it.

In general the dimension "the_end" should be excluded by default in the config file (.../spawn/common.yaml):
https://github.com/MarkusBordihn/BOs-Adaptive-Performance-Tweaks/blob/1.18.2/spawn/src/main/java/de/markusbordihn/adaptiveperformancetweaksspawn/config/CommonConfig.java#LL92C1-L93C98

I the issue only happens in "the_end" and you have this config setting, it should not be related to this mod.

**Comment by P3rf3ctXZer0** [comment]
I see. I will work on it then.

**Comment by P3rf3ctXZer0** [comment]
The entire changelog you provided completely affects me. I am going to close this as this is no longer specific. Also its hard to recreate.
