### ISSUE TITLE
Megatorch from Torchmaster not working anymore

### ISSUE THREAD

**Issue by ALainxD** [MarkusBordihn/BOs-Adaptive-Performance-Tweaks#5]
**Describe the bug**
The Mega torch which should prevent mob spawns in 64/32 block radius is not working anymore with the Mod, mob spawn regardless.

**To Reproduce**
Either
1. download Chroma technology 2
2. add Adaptive performance tweaks
3. Place down torchmaster Mega torch
4. see mobs spawn
or
1. Install Megatorch
2. add Adaptive performance tweaks
3. Place down torchmaster Mega torch
4. see mobs spawn

**Expected behavior**
Mobs shouldn't spawn inside the range of the Mega torch

**Additional context**

Modpack: 
Chroma technology 2

Additional mods: 
blocklog-1.0.jar
crashutilities-3.12.jar
itemblacklist-1.16.5-1.0.1.jar
kotlinforforge-1.16.0-obf.jar
mc2discord-forge-1.16.x-3.2.0.jar
notenoughcrashes-4.1.2+1.16.5-forge.jar
observable-0.2.1-forge.jar
worldedit-mod-7.2.5-dist.jar

**Comment by MarkusBordihn** [comment]
Thanks for the report. But I'm afraid that this is more an issue with Mega Torch itself and the 1.16.5 version.

According their code, they are only checking for the "LivingSpawnEvent.CheckSpawn" event, see: https://github.com/Xalcon/TorchMaster/blob/mc/1.16/src/main/java/net/xalcon/torchmaster/common/logic/entityblocking/EntityBlockingEventHandler.java#L24

But not for the LivingSpawnEvent.SpecialSpawn event or the EntityJoinWorldEvent (which exists but is disabled in their code), see:
https://github.com/Xalcon/TorchMaster/blob/mc/1.16/src/main/java/net/xalcon/torchmaster/common/logic/entityblocking/EntityBlockingEventHandler.java#L52

This means they are only blocking a fraction of the possible mob spawns. For example, if Adaptive Performance Tweaks is blocking the LivingSpawnEvent.CheckSpawn and the mob spawns over the LivingSpawnEvent.SpecialSpawn instead the mobs are not recognized by Mega Torch.

I see a similar issue report for InControl for the 1.16.5 version which could be related to this, see:
https://github.com/Xalcon/TorchMaster/issues/161

But I will check this more in detail to see, if there is anything wrong on my side.

**Comment by MarkusBordihn** [comment]
I added some additional compatibility for other mods in [adaptive_performance_tweaks_1.16.5-2.1.0.jar](https://www.curseforge.com/minecraft/mc-mods/adaptive-performance-tweaks/files/3728606), but this will not fix all issues with MegaTorch.

As I mentioned TorchMaster is not  considering the LivingSpawnEvent.SpecialSpawn event or the EntityJoinWorldEvent, which means it could be that you will still get some mobs over these spawn events until it's fixed in the TorchMaster mod itself.

**Comment by ALainxD** [comment]
Thank you very much

Will try it out :)
