### ISSUE TITLE
Crash server without adaptive_performance_tweaks_spawn

### ISSUE THREAD

**Issue by BlackAures1** [MarkusBordihn/BOs-Adaptive-Performance-Tweaks#50]
**Describe the bug**
If you try to start a server with an incomplete adaptive_performance_tweaks package, it crashes and requires adaptive_performance_tweaks_spawn to be installed. Is this mandatory? apt_spawn conflicts with InControl and often removes spawn completely in-game, so I don't want to use it. After removing adaptive_performance_tweaks the crash does not happen. The other mods work correctly

Crash report
[crash-2023-06-12_17.29.14-fml.txt](https://github.com/MarkusBordihn/BOs-Adaptive-Performance-Tweaks/files/11724816/crash-2023-06-12_17.29.14-fml.txt)

**Expected behavior**
adaptive_performance_tweaks_spawn no needed to adaptive_performance_tweaks

**Comment by MarkusBordihn** [comment]
Thanks for the report. If you have installed the [bundled](https://www.curseforge.com/minecraft/mc-mods/adaptive-performance-tweaks) version it's expect that all modules are used and required by the bundle.

If you only want to use specific modules, remove the bundled version and install the individuell packages instead like:

- [Core](https://legacy.curseforge.com/minecraft/mc-mods/adaptive-performance-tweaks-core) required by all modules
- [Game Rules](https://www.curseforge.com/minecraft/mc-mods/adaptive-performance-tweaks-gamerules)
- [Items](https://www.curseforge.com/minecraft/mc-mods/adaptive-performance-tweaks-items)
- ...

**Comment by BlackAures1** [comment]
adaptive_performance_tweaks (without prefixes) is bundled? Okay, it's a little obvious, but I was guessing that. I thought the version without the prefixes was Core

**Comment by MarkusBordihn** [comment]
The first few version was a single package. After I split it to several modules, the people ask me to put a  bundled version under the former name. For this historical reason the version without prefix is the bundled version.
