### ISSUE TITLE
Unknown Entity Name for Entity : LightningBoltWeatherNew

### ISSUE THREAD

**Issue by Chassx2** [MarkusBordihn/BOs-Adaptive-Performance-Tweaks#51]
[image](https://github.com/MarkusBordihn/BOs-Adaptive-Performance-Tweaks/assets/56740526/fed35871-eb06-4732-9310-6f8894436f98)

We are getting this in our error logs on the server. We have Weather 2 installed.

Weather 2 Mod:
https://www.curseforge.com/minecraft/mc-mods/weather-storms-tornadoes/files/4426524

Any idea what could be causing this?

**Comment by MarkusBordihn** [comment]
Thanks for the report. There is nothing to worry, it's just means that I should exclude the weather 2 entities from any checks to avoid side effects, which I will do with the next update.
