### ISSUE TITLE
APT: Spawn crashes on player join

### ISSUE THREAD

**Issue by markaabo** [MarkusBordihn/BOs-Adaptive-Performance-Tweaks#52]
**Describe the bug**
Adding the mod "Adaptive Performance Tweaks: Spawn" & Core ofc, makes the server crash when players join the server.

**To Reproduce**
1. Install the mod & other mods
2. Start the server
3. Join it
4. Boom server crashes

**Expected behavior**
For the server not to crash when joining it.

**Debugging**
`/aptweaks debug true` 
is not usable since i cant even connect to the server without it crashing.

**Is the issue happening in combination with other mods? (If yes, please provide a full list)**
I don't know if its conflicting with any mods of the other ones i have but here is the list:
```AdditionalEnchantedMiner-1.20.1-1201.0.10-SNAPSHOT
AI-Improvements-1.20-0.5.2
appleskin-forge-mc1.20.1-2.5.0
architectury-9.1.10-forge
canary-mc1.20(.1)-0.2.6
carryon-forge-1.20.1-2.1.0.1
chunksending-1.20.1-2.5
Chunky-1.3.92
cloth-config-11.1.106-forge
connectivity-1.20.1-4.4
create-1.20.1-0.5.1.d
CreativeCore_FORGE_v2.10.26_mc1.20.1
DripSounds-1.19.4-0.3.2
EdivadLib-1.20.1-2.0.0
ExtraStorage-1.20.1-4.0.0
farsight-1.20.1-3.2
FastLeafDecay-31
ferritecore-6.0.0-forge
gpumemleakfix-1.20.1-1.6
InventoryProfilesNext-forge-1.20-1.10.6
Jade-1.20-forge-11.1.4
jei-1.20.1-forge-15.2.0.22
JustEnoughResources-1.20.1-1.4.0.222
kotlinforforge-4.4.0-all
libIPN-forge-1.20-3.0.2
light-overlay-8.0.0-forge
Mekanism-1.20.1-10.3.9.homebaked-all
memoryleakfix-forge-1.17+-1.1.1
memorysettings-1.20.1-5.2
MouseTweaks-forge-mc1.20-2.25
NaturesCompass-1.20.1-1.11.1-forge
open-parties-and-claims-forge-1.20.1-0.19.0
pipez-1.20.1-1.1.3
polymorph-forge-0.49.0+1.20.1
Powah-5.0.0-alpha
refinedstorage-1.12.3
refinedstorageaddons-0.10.0
rubidium-0.6.5
ScalableCatsForce-3.3.0-build-0-with-library
ServerTabInfo-1.20-1.3.8
sfcr-1.7.5-mc1.20
simpletomb-1.20.1-1.0.18
smoothchunk-1.20.1-3.0
soundphysics-forge-1.20.1-1.1.1
spark-1.10.42-forge
structureessentials-1.20.1-2.9
XaeroPlus-Forge-1.20.1-2-WM1.30.6-MM23.5.0
```

**Additional context**
I have attached the crash logs and stuff from the server logs
[2023-07-10-1.log.gz](https://github.com/MarkusBordihn/BOs-Adaptive-Performance-Tweaks/files/12001851/2023-07-10-1.log.gz)
[debug-1.log.gz](https://github.com/MarkusBordihn/BOs-Adaptive-Performance-Tweaks/files/12001852/debug-1.log.gz)

**Comment by MarkusBordihn** [comment]
Thanks for the report. I currently working and testing a fix to avoid something like this for all versions.

**Comment by MarkusBordihn** [comment]
I just uploaded and updated version, which performs some additional checks to avoid this.

Please re-open this issue report, if you still see any crashes with a corresponding crash.log. Thanks.
