### ISSUE TITLE
Debug mode set to ALL

### ISSUE THREAD

**Issue by zekeflynn** [MarkusBordihn/BOs-Adaptive-Performance-Tweaks#56]
Hi I'm getting warning messages on the console saying the different modules debug is set to "ALL" and will impact performance and shouldn't be used on production environment, but I cannot find where to change this setting, if you could please point me in the right direction. Thanks.

**Comment by MarkusBordihn** [comment]
Thanks for your note. I need to adjust the note to make sure that for dedicated servers it's expected that the debug is enabled.
The warning just give you a hint that the mod ignores the debug all setting for performance reasons.
But as long you don't want to collect these debug information it's safe to ignore.

**Comment by MarkusBordihn** [comment]
Note: Adjusted the warn message to make sure that it's only a "warning" but no actually action is needed.
