### ISSUE TITLE
Mobs with PersistenceRequired tag despawning

### ISSUE THREAD

**Issue by marianyp** [MarkusBordihn/BOs-Adaptive-Performance-Tweaks#59]
**Describe the bug**
Mobs with the PersistenceRequired tag are despawning with this mod.

**To Reproduce**
Spawn a mob with the PersistenceRequired nbt tag set to true. I'm not sure under what case or scenario that triggers the mob to despawn but I'm assuming traveling several blocks away.

**Expected behavior**
Any entity with PersistenceRequired would not be despawned

**Comment by MarkusBordihn** [comment]
Thanks for the report. This and some other issues are fixed with version 11.x and higher.
