### ISSUE TITLE
Adaptive performance tweaks spawn not working 

### ISSUE THREAD

**Issue by funnycubeguy** [MarkusBordihn/BOs-Adaptive-Performance-Tweaks#64]
**Describe the bug**
Disabling hostile mob spawning in MinecraftSpawn.toml and the global limit in spawn.toml has no effect. I still can't spawn zombies in my world with a few players online. I can reproduce this my using ftb chunks and forceloading a bunch of chunk. I can kill all entities then use the zombie spawn egg and try to spawn zombies. It'll spawn 3 or 4 zombies before being blocked.

I have tried adjusting this limit to 1000 per player, world, server ect. 

I am using the all the mods 9 pack

**Comment by MarkusBordihn** [comment]
Please check https://github.com/MarkusBordihn/BOs-Adaptive-Performance-Tweaks/wiki/Troubleshooting and provide a debug.log which shows that the spawn model is blocking them.

Inside the debug.log you should see the exact reason why an entity is blocked and furthermore some general stats for this specific entity.
