### ISSUE TITLE
Villager zombification doesn't work with default spawn configs

### ISSUE THREAD

**Issue by ivxvm** [MarkusBordihn/BOs-Adaptive-Performance-Tweaks#65]
There is a vanilla mechanic to turn villagers into zombies to cure them later (for better trades).
With default configs villagers just die instead of turning into zombies.
Removing `minecraft:zombie_villager` from `HostileMobsList` in `/config/adaptive_performance_tweaks/spawn/MinecraftSpawn.toml` solved the issue immediately.

**Added**:
Actually, this wasn't enough. I had to add `allowList = ["minecraft:villager", "minecraft:zombie_villager"]` into `[General]` section of `spawn.toml`. And I think there is no need to touch `HostileMobsList` at all in this case as `spawn.toml` settings are more global and override everything.

**Comment by MarkusBordihn** [comment]
Thanks a lot for the report. I will try if I could track all villagers and ignore them if they are turned into zombies.

**Comment by MarkusBordihn** [comment]
The fix should be live in the next hours.

![image](https://github.com/user-attachments/assets/138bb5f8-1835-43a2-8f12-ed06bba15353)

Please keep in mind that even if it allows Zombification, it could be that the new Zombie Villager (with a different ID) is remove afterwards when the server load is to high or to many Zombie Villagers are already spawned.
```
[15:15:19] [Server thread/DEBUG] [APTweaks(Spawn)/]: [Zombie Villager Conversion] Convert Villager['Villager'/360, l='ServerLevel[world]', x=22.85, y=143.00, z=-598.90] to entity.minecraft.zombie_villager
[15:15:19] [Server thread/DEBUG] [APTweaks(Spawn)/]: [Zombie Villager Conversion] Allow join event for ZombieVillager['Zombie Villager'/376, l='ServerLevel[world]', x=22.85, y=143.00, z=-598.90] in minecraft:overworld
```
