### ISSUE TITLE
Bundled Version Broken

### ISSUE THREAD

**Issue by Ruok2bu** [MarkusBordihn/BOs-Adaptive-Performance-Tweaks#67]
**Describe the bug**
The bundled version throws errors in server console on that the modules are missing.

**To Reproduce**

1. Download bundled version from https://www.curseforge.com/minecraft/mc-mods/adaptive-performance-tweaks
2. Install to server
3. Restart
4. Facepalm when it throws error message and then install non bundled version instead.

**Expected behavior**
Bundled version should include all modules and not show error message requiring modules to be installed.

**Screenshots**
error during pre-loading phase
net.minecraftforge.fml.ModLoadingException: Mod �eadaptive_performance_tweaks�r requires �6adaptive_performance_tweaks_items�r �o11.0.0 or above, and below 12.0.0�r
�7Currently, �6adaptive_performance_tweaks_items�r�7 is �o�nnot installed

It shows this for all the modules (replacing module name with appropriate module)

**Comment by ShadowTech99001** [comment]
Facepalm lmao

**Comment by MarkusBordihn** [comment]
The bundled version uses the CurseForge dependency feature. You can see the dependencies here: [CurseForge Dependencies](https://www.curseforge.com/minecraft/mc-mods/adaptive-performance-tweaks/relations/dependencies).

This doesn't mean it's a single file with all modules automatically included.

Creating a single downloadable version that includes all updated modules would take a significant amount of time after each update. Therefore, I've utilized CurseForge's built-in dependency system.

If you download just one file without manually including the necessary dependencies, it will fail with a shared error message.

To avoid this, you should either use the CurseForge system to create a server package that handles dependencies automatically or manually download each dependency yourself.
