### ISSUE TITLE
Non-Mob Entities Deleted`

### ISSUE THREAD

**Issue by UdderlyEvelyn** [MarkusBordihn/BOs-Adaptive-Performance-Tweaks#73]
In the spawn module (I use the stand-alone one) the corpses from the Corpse mod are deleted by default. Not sure why non-mobs are being deleted in the first place, but the corpses should probably be a built-in exception since the corpse mod is common.

**Comment by MarkusBordihn** [comment]
Thanks for the report, I will add them to the exclude list.
