### ISSUE TITLE
1.19.2 Endergetic Expansion Puffbug (re-open)

### ISSUE THREAD

**Issue by Enterprise12nx01** [MarkusBordihn/BOs-Adaptive-Performance-Tweaks#75]
Just re-opening issue #72 
The dev has said this is an adaptive performance tweaks issue, as these mobs were present before bees were ever introduced and only occurs with this mod
https://github.com/team-abnormals/endergetic/issues/262#issuecomment-2397821414

**Comment by MarkusBordihn** [comment]
I left a comment on their response.
Could you please let me know where you downloaded their mod ?

I want to check their  .jar more in detail, especially when there is an older version of their mod.

**Comment by Enterprise12nx01** [comment]
> I left a comment on their response. Could you please let me know where you downloaded their mod ?
> 
> I want to check their .jar more in detail, especially when there is an older version of their mod.

i appreciate you trying to fix the issue that is probably not on your side, i downloaded it on curseforge using version 4.0.0 1.19.2
https://www.curseforge.com/minecraft/mc-mods/endergetic/files/5146370

they only have one version for 1.19.2 it seems

**Comment by MarkusBordihn** [comment]
Thanks for sharing.

Duplicated issues related to https://github.com/MarkusBordihn/BOs-Adaptive-Performance-Tweaks/issues/72
