### ISSUE TITLE
⚠️ 1.16 Port Request // APT; Mods (oops) ⚠️

### ISSUE THREAD

**Issue by Cixon** [MarkusBordihn/BOs-Adaptive-Performance-Tweaks#8]
**Additional context**
Hello! Good evening!
Now I did read that a 1.16 version is not currently planned. However I just want to ticket my two cents. I currently utilize your APT mod (not to get confused with apartment) and I gotta say you truly know your stuff and do it well..so well I haven’t really complained about anything performance wise from entities so kudos to you!

My primary reason for this post is because I want to enjoy both APT and player tweaks for servers. As we all know, vanilla servers don’t perform well under most circumstances. I tried Roadrunner mod but player stability just isn’t efficient enough for my 1.16 server. I currently do not have the time and management required to transfer the world over (houses & mod-pack included) to 1.18 and would love a 1.16 port.

**Comment by Cixon** [comment]
Thank you so much and at any rate, best regards!

**Comment by MarkusBordihn** [comment]
Sorry, but I'm not really understand your use-case here.

The former 1.16.5 version of APT, like https://www.curseforge.com/minecraft/mc-mods/adaptive-performance-tweaks/files/3750103
Includes a lot of tweaks which are not included in the current 1.18.x version.

The 1.16.5 version includes nearly all modules from the 1.18.x and some more aggressive optimization which could be enabled/disabled in the config file.
The 1.18.x version is separated by module and includes only the less aggressive optimization to make sure it works better with other optimization mods. For example the latest 1.18.2 will not automatically adjust the view distance in favour of the [dynamic view](https://www.curseforge.com/minecraft/mc-mods/dynamic-view) and [farsigh](https://www.curseforge.com/minecraft/mc-mods/farsight) mod.

Please let me know which "feature" you exactly missing in the 1.16.5 version from the 1.18.x version ?

In general not all optimization makes sense in both version, so there are some which only makes sense in 1.16.x and some other which only makes sense in 1.18.x.
