### ISSUE TITLE
How to change the configuration file, it will also generate a new one

### ISSUE THREAD

**Issue by tusir233** [MarkusBordihn/BOs-Adaptive-Performance-Tweaks#9]
How to change the configuration file, it will also generate a new one

**Comment by MarkusBordihn** [comment]
Could you please let me know which version / module your are using and which config file / entry you try to adjust ? Thanks.

**Comment by tusir233** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
